# Generated by Django 3.1.2 on 2020-12-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sort', models.IntegerField(blank=True, default=99999)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='one word for title alias', null=True, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('subtitle', models.CharField(blank=True, default='', max_length=1024)),
                ('note', models.TextField(blank=True, default='')),
                ('component', models.CharField(blank=True, default='', max_length=1024)),
                ('context', models.CharField(blank=True, default='', max_length=1024)),
                ('code', models.TextField(blank=True, default='', null=True)),
                ('codelog', models.TextField(blank=True, default='', null=True)),
                ('html', models.TextField(blank=True, default='', null=True)),
                ('js', models.TextField(blank=True, default='', null=True)),
                ('css', models.TextField(blank=True, default='', null=True)),
                ('style', models.TextField(blank=True, default='', null=True)),
                ('json', models.TextField(blank=True, default='', null=True)),
                ('visible', models.CharField(blank=True, default='', max_length=1024)),
                ('layout', models.CharField(blank=True, default='', max_length=1024)),
                ('separator', models.CharField(blank=True, default='', max_length=1024)),
                ('tag', models.CharField(blank=True, default='', max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum/comment/%Y_%m_%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id_sort', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sort', models.IntegerField(blank=True, default=99999)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='one word for title alias', null=True, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('subtitle', models.CharField(blank=True, default='', max_length=1024)),
                ('note', models.TextField(blank=True, default='')),
                ('component', models.CharField(blank=True, default='', max_length=1024)),
                ('context', models.CharField(blank=True, default='', max_length=1024)),
                ('code', models.TextField(blank=True, default='', null=True)),
                ('codelog', models.TextField(blank=True, default='', null=True)),
                ('html', models.TextField(blank=True, default='', null=True)),
                ('js', models.TextField(blank=True, default='', null=True)),
                ('css', models.TextField(blank=True, default='', null=True)),
                ('style', models.TextField(blank=True, default='', null=True)),
                ('json', models.TextField(blank=True, default='', null=True)),
                ('visible', models.CharField(blank=True, default='', max_length=1024)),
                ('layout', models.CharField(blank=True, default='', max_length=1024)),
                ('separator', models.CharField(blank=True, default='', max_length=1024)),
                ('tag', models.CharField(blank=True, default='', max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum/main/%Y_%m_%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id_sort', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Forumsub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sort', models.IntegerField(blank=True, default=99999)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='one word for title alias', null=True, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('subtitle', models.CharField(blank=True, default='', max_length=1024)),
                ('note', models.TextField(blank=True, default='')),
                ('component', models.CharField(blank=True, default='', max_length=1024)),
                ('context', models.CharField(blank=True, default='', max_length=1024)),
                ('code', models.TextField(blank=True, default='', null=True)),
                ('codelog', models.TextField(blank=True, default='', null=True)),
                ('html', models.TextField(blank=True, default='', null=True)),
                ('js', models.TextField(blank=True, default='', null=True)),
                ('css', models.TextField(blank=True, default='', null=True)),
                ('style', models.TextField(blank=True, default='', null=True)),
                ('json', models.TextField(blank=True, default='', null=True)),
                ('visible', models.CharField(blank=True, default='', max_length=1024)),
                ('layout', models.CharField(blank=True, default='', max_length=1024)),
                ('separator', models.CharField(blank=True, default='', max_length=1024)),
                ('tag', models.CharField(blank=True, default='', max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum/appname/%Y_%m_%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id_sort', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sort', models.IntegerField(blank=True, default=99999)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='one word for title alias', null=True, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('subtitle', models.CharField(blank=True, default='', max_length=1024)),
                ('note', models.TextField(blank=True, default='')),
                ('component', models.CharField(blank=True, default='', max_length=1024)),
                ('context', models.CharField(blank=True, default='', max_length=1024)),
                ('code', models.TextField(blank=True, default='', null=True)),
                ('codelog', models.TextField(blank=True, default='', null=True)),
                ('html', models.TextField(blank=True, default='', null=True)),
                ('js', models.TextField(blank=True, default='', null=True)),
                ('css', models.TextField(blank=True, default='', null=True)),
                ('style', models.TextField(blank=True, default='', null=True)),
                ('json', models.TextField(blank=True, default='', null=True)),
                ('visible', models.CharField(blank=True, default='', max_length=1024)),
                ('layout', models.CharField(blank=True, default='', max_length=1024)),
                ('separator', models.CharField(blank=True, default='', max_length=1024)),
                ('tag', models.CharField(blank=True, default='', max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='forum/page/%Y_%m_%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('depth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_page_replies', to='forum.page')),
                ('parent', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.forumsub')),
            ],
            options={
                'ordering': ('id_sort', 'id'),
            },
        ),
    ]
